/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppProductionRouteImport } from './routes/_app/production'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppAuditRouteImport } from './routes/_app/audit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/production': typeof AppProductionRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/finance': typeof AppFinanceRoute
  '/inventory': typeof AppInventoryRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/production': typeof AppProductionRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/finance'
    | '/inventory'
    | '/notifications'
    | '/pos'
    | '/production'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/finance'
    | '/inventory'
    | '/notifications'
    | '/pos'
    | '/production'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/audit'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/finance'
    | '/_app/inventory'
    | '/_app/notifications'
    | '/_app/pos'
    | '/_app/production'
    | '/_app/products'
    | '/_app/purchases'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRoute,
  AppProductionRoute: AppProductionRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
